server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务器地址
mybatis:
  type-aliases-package: me.longDay.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    me.longDay: debug
  pattern:
    dateformat: MM-dd HH:mm:ss


#eureka:
#  client:
#    service-url: #Eureka 的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka